# Generated by Django 5.0.2 on 2024-02-26 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algo', '0003_algorithm'),
    ]

    operations = [
        migrations.CreateModel(
            name='Problem_site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Data_structure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url_name', models.CharField(max_length=255)),
                ('theme', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='algo.data_structures_theme')),
            ],
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('difficulty', models.IntegerField()),
                ('url', models.URLField()),
                ('tags_algo', models.ManyToManyField(to='algo.algorithm')),
                ('tags_ds', models.ManyToManyField(to='algo.data_structure')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='algo.problem_site')),
            ],
        ),
    ]
