# Generated by Django 5.0.2 on 2024-02-26 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algo', '0004_problem_site_data_structure_problem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='tags_ds',
            field=models.ManyToManyField(blank=True, to='algo.data_structure'),
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('tag_algo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='algo.algorithm')),
                ('tag_ds', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='algo.data_structure')),
            ],
        ),
    ]
