# Generated by Django 5.0.2 on 2024-02-26 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algo', '0006_alter_article_tag_algo_alter_article_tag_ds_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='tags_algo',
            field=models.ManyToManyField(blank=True, to='algo.algorithm'),
        ),
    ]
