# Generated by Django 5.0.2 on 2024-02-27 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('algo', '0007_alter_problem_tags_algo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Algo_theme',
            new_name='AlgoTheme',
        ),
    ]
