# Generated by Django 5.0.2 on 2024-02-27 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('algo', '0008_rename_algo_theme_algotheme'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Data_structures_theme',
            new_name='DataStructuresTheme',
        ),
    ]
