# Generated by Django 5.0.2 on 2024-02-27 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('algo', '0009_rename_data_structures_theme_datastructurestheme'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Data_structure',
            new_name='DataStructure',
        ),
        migrations.RenameModel(
            old_name='Problem_site',
            new_name='ProblemSite',
        ),
    ]
