# Generated by Django 5.0.2 on 2024-02-27 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('algo', '0010_rename_data_structure_datastructure_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DataStructuresTheme',
            new_name='DataStructureTheme',
        ),
    ]
