# Generated by Django 5.0.2 on 2024-03-05 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('algo', '0012_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='problem',
            options={'ordering': ['difficulty']},
        ),
    ]
