# Generated by Django 5.0.2 on 2024-03-07 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('algo', '0013_alter_problem_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='algorithm',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='datastructure',
            options={'ordering': ['name']},
        ),
    ]
